version: '3.4'

networks:
  botnetwork:

services:
  influxdb:
    image: influxdb:1.3
    container_name: influxdb
    restart: always
    networks:
      - botnetwork
    ports:
      - 8086:8086
      - 8082:8082
      - 8083:8083
      - 8089:8089/udp
    volumes:
      - influxdb-volume:/vol01/Docker/market
    environment:
      - INFLUXDB_DB=market
      - INFLUXDB_USER=market
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=*****
      - INFLUXDB_ADMIN_PASSWORD=*****
  market:
    image: ${DOCKER_REGISTRY-}market
    depends_on: [influxdb]
    networks:
      - botnetwork
    ports:
      - "5101:80"
    environment:
      - INFLUXDB_ADMIN_USER=*****
      - INFLUXDB_ADMIN_PASSWORD=*****
      - INFLUXDB_ENDPOINT_URI=http://influxdb:8086/
      - FirstRunAfter=25
      - Interval=60
    build:
      context: .
      dockerfile: Market/Dockerfile
  strategy:
    image: ${DOCKER_REGISTRY-}strategy
    depends_on: [influxdb]
    networks:
      - botnetwork
    ports:
      - "5102:80"
    environment:
      - INFLUXDB_ADMIN_USER=*****
      - INFLUXDB_ADMIN_PASSWORD=*****
      - INFLUXDB_ENDPOINT_URI=http://influxdb:8086/
    build:
      context: .
      dockerfile: Strategy/Dockerfile

volumes:
  influxdb-volume:
    external: true
