version: '3.4'

networks:
  marketnetwork:

services:
  influxdb:
    image: influxdb:1.3
    container_name: influxdb
    restart: always
    networks:
      - marketnetwork
    ports:
      - 8086:8086
      - 8082:8082
      - 8083:8083
      - 8089:8089/udp
    volumes:
      - influxdb-volume:/vol01/Docker/market
    environment:
      - INFLUXDB_DB=market
      - INFLUXDB_USER=market
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Welcome#123456 
  market:
    image: ${DOCKER_REGISTRY-}market
    depends_on: [influxdb]
    networks:
      - marketnetwork
    build:
      context: .
      dockerfile: Market/Dockerfile


volumes:
  influxdb-volume:
    external: true
